cleaned up
dannyneup/ProtectiveClothingManagement pull request #1
Opened 2023-03-31 16:00 UTC by dannyneup

2023-03-31 20:00 UTC, HansenBerlin requested changes
Kennst mich ja. Mecker mecker, auch wenn alles in allem alles ok ist. So auch hier: Ist schon ein feiner Start und du hast dir auch echt viel vorgenommen mit Clean Arch, Patterns usw. In dem Kontext hast du da schon echt viel richtig gemacht. Die Kommis sollen das nicht negieren, aber bin da halt pragmatisch und schreibe da wo mir was auffällt. Stell dir einfach zwischendurch hier und da nen Kommi vor "Gut umgesetzt" oder so. ;-)
Wenn was unklar ist: am besten hier antworten direkt auf die Kommentare. Dann vergess ichs nicht.

2023-03-31 20:00 UTC, HansenBerlin commented on Core/Entities/IItem.cs
Brauchen die wirklich alle nen Setter? Gilt auch für alle anderen Models. Wenn da nur der Jsonresponse drauf gemappt wird reicht (glaube ich) auch init. Kannste ja mal ausprobieren. 
Zweitens: setze default values (außer bei ints und bools), also leeren string um NPEs zu vermeiden (gilt natürlich nur für die Implementierungen)
Drittens: wenn es ne required property ist, kannst du das mit selbigem Keyword annotieren.

2023-03-31 20:00 UTC, HansenBerlin commented on Core/Entities/IItemType.cs
Hinsichtlich Models und Interfaces hatte ich schonmal irgendwann was geschrieben. Reine Models ohne Logik (also DTOs) brauchen kein Interface, weil du da ja keine Rückgaben mocken musst. Wenn du dann testen willst gibst du entweder den Implementierungen ihre Values oder nutzt ne Lib wie zB NSubstitute die das übernimmt.

2023-03-31 20:00 UTC, HansenBerlin commented on Core/Entities/IOrder.cs
> +    string OrderNumber { get; set; }
Warum ist ne OrderNumber ein String? Entweder stimmt der Datentyp nicht oder die Benneung ist irreführend.

2023-03-31 20:00 UTC, HansenBerlin commented on Core/Entities/IPerson.cs
> +    int PersonnelNumber { get; set; }
typo: Personell oder Personel aber nicht mit nn :-)

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.Application/Enums/Status.cs
Denk dran das bei Enums immer der erste Value als default gesetzt ist (null jibbet da nicht). Also wenn Pending der default sein soll, alles schick, ansonsten müsstest du noch nen dritten (an erster Stelle) einführen.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.Application/Interfaces/IRepository.cs
> +    Task<IEnumerable<TResponse>> GetAll(Dictionary<string, string>? queries = default);
Warum nullable? Das zieht sich dann wie ne Seuche durch die Aufrufer. Lieber gleich am Anfang handeln.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.Application/Interfaces/IRepository.cs
> +    Task<TResponse> Get(int id, Dictionary<string, string>? queries = default);
s.o.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.Infrastructure/Repositories/Repository.cs
> +    private TResponse _type;
Dead Code?

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.Infrastructure/Repositories/Repository.cs
> +    public async Task<IEnumerable<TResponse>> GetAll(Dictionary<string, string>? queries = default)
nullable

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.Infrastructure/Repositories/Repository.cs
> +    private string ExtractQuery(Dictionary<string, string>? queries)
Wo haste das denn abgeschrieben? Oder war ich das?  ;-) Und wofür ist es?

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.Infrastructure/RequestModels/ItemCategoryRequest.cs
> +public class ItemCategoryRequest
Hier sind jetzt default values. Besser. :-) Sollte überall so sein, schreibe das jetzt nicht jedesmal hin.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.Infrastructure/ResponseModels/PersonResponse.cs
Da sind wir wieder bei Request und Response. Sind die nicht genau gleich? Dann nimm auch nur ein Model. Kannst auch records nehmen wenn die Daten nicht verändert werden (was nicht der Fall sein sollte). Die sind weniger boilerplatig und  genau für solche Zwecke gedacht (dumme DTOs, Prop Names = json Response) und wenier memory intensiv. Aber können halt nur einmal inital mit ner Art Pseudokonstruktor ihre Values bekommen.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Autocompletes/ItemCategoryAutocomplete.razor
> +                 Value="ItemCategory" ValueChanged="OnValueChanged"
Formatierung inkonsistent

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Autocompletes/ItemCategoryAutocomplete.razor.cs
> +    [Parameter] public ItemCategory ItemCategory { get; set; }
Gabs dazu nicht irgendwo ein Interface? Nicht das man das bräuchte wenns nur ein Model ist, aber wenn du die schon baust benutz sie auch.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Autocompletes/ItemCategoryAutocomplete.razor.cs
> +    [Parameter] public List<ItemCategory> ItemCategories { get; set; }
NPE Alarm wenn der Parameter nicht gesetzt wird. Entweder =new() oder mit [Parameter, EditorRequired] dem armen Entwickler sagen das der Parameter benötigt wird (schmeißt glaube ich ne Warning und keine Exception aber immerhin)

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Autocompletes/TrainingAutocomplete.razor
> +<MudAutocomplete T="Training"
s.o.: Formatierung inkonsistent

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Autocompletes/TrainingAutocomplete.razor.cs
Die Komponente ist doch oben 1:1. Ego duplicate code.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Autocompletes/TrainingAutocomplete.razor.cs
> +        Training = Training;
Inner hides Outer.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Autocompletes/TrainingTypeAutocomplete.razor
s.o., Formatierung und Duplikat

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Autocompletes/TrainingTypeAutocomplete.razor.cs
zum dritten Mal? Falls Git wieder wa löscht? :-)

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingDetailsDialog.razor
Ist zweimal fast der gleiche Code innerhalb einer (dadurch sehr großen) Komponente. Würde ich ne eigene draus machen, die du dan hier zweimal aufrufst.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingDetailsDialog.razor.cs
> +    private const string _height = "30vw";
Konstanten über readonlys (Konvntion) und immer groß, auch wenn private.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingDetailsDialog.razor.cs
> +    [Parameter] public List<Person> Persons { get; set; }
s.o. NPE

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingEditorDialog.razor.cs
> +    private MudForm _form;
alle Felder: Formatierung (Lücken), Reihenfolge (erst Konstanten, dann Felder, dann Props usw, immer von private nach public)

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingEditorDialog.razor.cs
> +    private LoadOutPart? _loadOutPartBeforeEdit;
nullable

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingEditorDialog.razor.cs
> +    public Training Training { get; set; } = new()
Warum so? Wenn du direkt in der Kompoenente der Prop nen default Value geben würdest wäre das nicht nötig.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingEditorDialog.razor.cs
> +    [Parameter] public List<Training> Trainings { get; set; }
s.o., NPE (schreibe ich ab jetzt nicht mehr hin, check mal alle Listen durch)

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingEditorDialog.razor.cs
> +        void RestoreCategory()
Nur weils geht heißt es nicht das mans machen soll. Methode in der Methode is nicht so schön. Is ja hier kein Javasript. ;-)

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingEditorDialog.razor.cs
> +        StateHasChanged();
Das hier immer StateHasChanged aufgerufen werden muss smellt ein wenig.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingEditorDialog.razor.cs
> +    private bool NoCategoriesRemaining()
bools mit Is... oder Has... beginnen

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Dialogs/TrainingEditorDialog.razor.cs
> +}
Insgesamt ne Mörderkomponente, die wahnsinnig viel Logik enthält. Klassischer Fall für ein View Model (oder halt Controller). Ist so sehr schwer nachvollziehbar, zumal du viel mit globalen Variablen arbeitest. Das wäre ein klassischer Fall für ein dickes Refactoring mit Extractions. Hätte man mal Unittests, wa. ;-)

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Lists/TrainingList.razor
> +        <col/>
Hmmmm. Das sieht bisschen nach Workaround aus. Aber vielleicht hats ja nen Grund.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Lists/TrainingList.razor.cs
> +    private async void OnRowClick(TableRowClickEventArgs<Training> rowClickEvent)
Da diese und die nächste Methode nur nen Wrapper für ein einzelnes Command sind kannste das auch direkt als Lamda aufrufen.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Lists/TrainingList.razor.cs
> +    private async void OnRowClick(TableRowClickEventArgs<Training> rowClickEvent)
async was??? 😈

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Lists/TrainingList.razor.css
> +.smallWidthColumn {
Nicht ganz einheitlich, aber in aller Regel verwnedet man für css kein camelCase sondern schreibt alles klein und verbindet mit -

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Components/Lists/TrainingList.razor.css
> +.moreIcon button {
Warum heißt die Klasse Icon und ist eigentlich ein Button? Dann nenn es doch custom-button oder so.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Controller/ListItemFilterController.cs
Warum statisch? Und das Ding ruft ja auch selbst statische Klassen auf. Dadurch wird es komplett untestbar. Zudem zeigst du über DI auch welche Komponenten wohin gehören  und wo verwendet werden sollen.  Zudem das Ding so wie es gebaut ist ja ein klassischer "Service" ist der konsumiert wird.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Controller/ListItemFilterController.cs
> +            if (itemMatches) filteredItems.Add(item);
on statement per line

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Models/ItemCategory.cs
> +    {
Die sollte eigentlich daselbe tun wie die dadrüber, ergo die erste kann weg. Equals vergleicht ja schon value equality und eben nicht reference equality.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Models/ItemCategory.cs
> +    public override int GetHashCode()
Warum. Warum nur? Wenn du ein Objekt eineindeutig erkennen willst nimm ne Guid.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Models/LoadOutPart.cs
Öhhh. Ist ja genau das gleiche.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Models/Person.cs
Sehe ich zum dritten Mal.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Models/Training.cs
noch ein alter Bekannter

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Index.razor
Das training response sieht etwas verloren aus. Soll das so?

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor
> +        <MudIconButton Icon="@Icons.Material.Filled.AddCircle" @onclick="OnAddButtonClicked"/>
@onclick "geht immer", weil das die JS Methode ist. Der MUdButton hat aber auch ne eigene (OnClick). .net params sind immer groß, nativ JS params klein. Wenn es beide gibt immer den .net param bevorzugen.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +    [Inject] public IRepository<TrainingResponse, TrainingRequest> TrainingRepository { get; set; }
Hier kann was nicht passen. Warum sind 4 Repositories in einer Komponente?

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +        async Task GetTrainings()
s.o. nested methods. NoNo.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +            if (!itemCategoryResponses.FirstOrDefault().IsResponseSuccess)
Sowas gehört nicht in die Komponente. Du würdest nen Controller bauen der Messages baut wenn solch Sachen passieren. Die Komponenten subscriben bei dem und zeigen dynamisch die Snackbar an. Zumal das "behandeln" des http responses hier viel zu spät ist. Passt schon mit dem Bool, viel mehr muss Nutzer nicht wissen. Aber das Handling muss wie gesagt früher erfolgen. In MVVM: Model kennt Repo und informiert Viewmodel über response (über callback). Viewmodel baut die Message zuammen und informiert view (callback). 
Oder in MVC: Controller ruft Srvice auf (repository) und schreibt in Model, Model updated über event subscription oder callback die View.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +            _itemCategories = itemCategoryResponses.Select(x => new ItemCategory
Why? Ist halt sone Pseudo-Deepcopy.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +        var dialogParams = new DialogParameters
Ist schon der dritte Dialog glaub ich. Bau dir dafür nen Service. Aufruf dialogService.Show(x, y, z). Kannst auch nen enum übergeben welcher Typ (Warning, Error, Info), plus Content.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +            {
s.o. warum die Copy? Was BTW nur funktioniert weil du hier primitive Datentypen hast. Das Konzept explodiert sobald du reference objects verwendest. Wieso nimmst du nicht einfach die Responses? Wenn du mit IEnums arbeitest sind die eh readonly.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +    private List<ItemCategory> _itemCategories;
Nur Hinweis, weil du mal Listen, mal IEnumerables nimmst. Letzteres gilt als performanter (durch den Iterator), was aber nur dann zutrifft wenn du nur einmal (oder selten) iterierst. Sobald das öfter vorkommt (oder gar in vrschachtlten Loops) ist die Liste deutlich performanter, weil die am Anfang einmal auf den Heap geschrieben wird, dafür aber dann die Referenzen auf jedes Item bekannt sind. IEnums müssen jedesmal neu iterieren, Nur als Background um die Entscheidung besser treffen zu können was wann besser ist. Zudem haben Listen paar mehr Methoden, weil IEnm halt nur die Basisklasse/Interface für Collections ist. 
Heißt nicht das hier die Liste falsch ist, war mir nur aufgefallen dass das etwas willkürlich mal so mal so verwendet wird. :-)

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +            _trainings.Append(training);
Warnung ignoriert? Sollte eigentlich keine Auswirkung haben, weil immutable. append != add (was es in IEnum nicht gibt)

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +    private async Task ShowDetailDialog(Training training)
noch ein Dialog für den Service. Ich sehe förmlich schon den aufgeräumten Code vor mir. :-)

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +    private async Task EditTraining(Training training)
80 Zeilen mit sub methods. DAAAANNNNNY! Ist aber dankbar zum refactorn. Extract, umbenennen, zwischendurch "testen". Dann macht es Spaß das ausenanderzupflücken.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +        var loadOutQueries = new Dictionary<string, string>
getloadout, deletetraining. Merkste was? Du reproduzierst hier grad dein Repository und baust hier einfach Wrapper. Die sind nicht immer schlecht und manchmal nötig, aber in dem Fall super redundant und unnötiger Boilerplate. Die Komponente muss auf jeden aufgeteilt werden, alleine die 4 Repositories sind Alarmstufe rot-schwarz. Und ich würd hier auch wider an ein Viewmodel denken, was als Intermediate zwischen View und Datenschicht vermittelt.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/Trainings.razor.cs
> +        var ErrorMessage = string.Format(Localization.TWithNameNotSuccessfullyDeleted, Localization.training,
Die Errormessage hab ich nach Betrachtung der Komponente grad im Kopf. Aber kleingeschrieben.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/_Host.cshtml
> +<component type="typeof(App)" render-mode="Server"/>
Kollege Neubauer. Haste dir das gut überlegt? 
1. Warum?
2. Nein
3. Wenn doch: warum?

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Pages/_Layout.cshtml
> +    <link href="Pcm.WebUi.styles.css" rel="stylesheet">
Wenn du ne globale css willst (neben den isolierten), dass ist die site.css unter www. Reicht meistens aus.

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Program.cs
> +    config.SnackbarConfiguration.PreventDuplicates = false;
Sind die nicht eh per default false?

2023-03-31 20:00 UTC, HansenBerlin commented on Pcm.WebUi/Shared/MainLayout.razor
>              <img src="logo.svg" width="40px" style="margin-left: 10px"/>
semikolon (geht auch ohne wenn letzter Eintrag, vergisst man dann aber gern wenn man mehr hinzufügt und ist einfach best practice)

2023-03-31 22:03 UTC, dannyneup commented on Core/Entities/IItemType.cs
In dem Fall muss ich doch aber Interfaces nutzen, weil die Implementierung ja erst in der UI stattfindet..? 
Genauso im Infrastructure Projekt. Da hab ich ja die Repositoryinterfaces, welche ich ja für die dependency injection brauche. Und die "special-repositories" (TrainingRepository) brauchen ja wiederum entweder models oder interfaces für die returns. Da Infrastructure aber nicht von der UI Abhängen soll, hab ich die Interfaces gebaut. (der vollständigkeitshalber alle..)

2023-03-31 22:08 UTC, dannyneup commented on Core/Entities/IPerson.cs
> +    int PersonnelNumber { get; set; }
Ne, hab grad nochmal nachgeguckt. Stimmt tatsächlich so. Ich muss aber zugeben, dass es etwas gewöhnungsbedürftig aussieht ;)

2023-04-01 07:29 UTC, HansenBerlin commented on Core/Entities/IPerson.cs
> +    int PersonnelNumber { get; set; }
Tatsächlich. So lernen beide was. :-)

2023-04-01 23:56 UTC, dannyneup commented on Pcm.WebUi/Pages/_Host.cshtml
> +<component type="typeof(App)" render-mode="Server"/>
fixed 163327d74c2d13a3488df87b23bc49fbb123af63

2023-04-01 23:59 UTC, dannyneup commented on Pcm.WebUi/Shared/MainLayout.razor
>              <img src="logo.svg" width="40px" style="margin-left: 10px"/>
fixed: 05efbef83def98dfd0a36a1cfc99d39264b7a044

2023-04-02 11:59 UTC, dannyneup commented on Pcm.Infrastructure/ResponseModels/PersonResponse.cs
Der einzige Unterschied ist bei den Response- und Requestmodels meist nur die id. Per Definition hat die in nem post ja nichts zu suchen. Der Workaround mit id=0 würde gehen aber ist das clean...?

2023-05-11 13:17 UTC, merged